name: Do automatic release

on:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking auto code...
        uses: actions/checkout@v2

      - name: Fetching node version...
        id: node_version
        run: echo "::set-output name=tag::$(curl -sL https://api.github.com/repos/nodejs/node/releases/latest | jq -r '.tag_name')"

      - name: Fetching node last release URL...
        id: node_url
        run: echo "::set-output name=url::$(curl -sL https://api.github.com/repos/nodejs/node/releases/latest | jq -r '.html_url')"

      - name: Creating release...
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.node_version.outputs.tag }}
          release_name: Node ${{ steps.node_version.outputs.tag }}
          body: |
            Installs [Node ${{ steps.node_version.outputs.tag }}](${{ steps.node_url.outputs.url }})
          draft: false
          prerelease: false
        continue-on-error: true
